### ISSUE TITLE
How to PROPERLY create a text channel?

### ISSUE THREAD

**Issue by 07v** [shayypy/guilded.py#24]
When making a utiltiy bot, I cannot figure out or find a way to make a channel? 
- How do I create one without an `Invalid Syntax` error?

**Comment by shayypy** [comment]
This is due to user error and not one with the library, as `SyntaxError` is raised before any code is executed.

**Comment by 07v** [comment]
> This is due to user error and not one with the library, as `SyntaxError` is raised before any code is executed.

I already fixed it, I didnt read the documentation correctly
