### ISSUE TITLE
Wrong license message

### ISSUE THREAD

**Issue by TheGenocides** [shayypy/guilded.py#26]
# Wrong license message

So in some files this include but not limited to: [backoff.py](https://github.com/shayypy/guilded.py/blob/master/guilded/backoff.py), the license message is still belongs to Rapptz while LICENSE file is shay (shayypy). Is this on purpose?

**Comment by sairam4123** [comment]
I guess the file is taken from discord.py, so that's why it's license is unedited..

**Comment by shayypy** [comment]
Yes - I did not write any part of this file. 

> while LICENSE file is shay (shayypy).

You may notice that the project's LICENSE actually includes both of our licenses due to how much of discord.py's code this project inhabits.
