### ISSUE TITLE
Cant send Embeds

### ISSUE THREAD

**Issue by Jigsaw88** [shayypy/guilded.py#33]
**Describe the bug**
You cant send Embeds.

**To Reproduce**
Code:
`@bot.command()
async def EmbedTest(ctx):
    embed = guilded.Embed(Title="Test Title", desciption="Test Description", color=0x00ff00)
    embed.add_field(name="Field 1", value="Field 1 Value", inline=False)
    await ctx.send(embed=embed)`

**Screenshots**
![image](https://user-images.githubusercontent.com/71355908/167610292-df1491c6-cd87-4c18-aea7-18dd0e04f181.png)

Code:
![image](https://user-images.githubusercontent.com/71355908/167609628-f5ace30b-067a-45f1-a303-dc8f672432e7.png)

**Environment**
 - OS: Windows 10
 - Python version: 3.9
 - Library version: 1.0.0a0

**Comment by shayypy** [comment]
Are you on the latest commit? Embeds have only been supported since https://github.com/shayypy/guilded.py/commit/2eaf9dfbf645b9ed97f606f20229c165431f8b8c

**Comment by Jigsaw88** [comment]
yea thats the issue, i used the version from pypi.
I updated it and now it works, thanks.
