### ISSUE TITLE
Embeds not Sending

### ISSUE THREAD

**Issue by Reedeht** [shayypy/guilded.py#36]
**Describe the bug**
When attempting to send embeds, that have been made similar to in discord.py, you get a series of errors related to embeds.

**To Reproduce**
How to reproduce is in screenshot, but it is applicable to all embed modifications

**Expected behavior**
Bot would send an embed with gold colouring, and a single field, with Test as a title and Test as Content.

**Actual behavior**
Errors sent to console, copy and paste below
Ignoring exception in command test:
Traceback (most recent call last):
  File "guilded/ext/commands/core.py", line 83, in wrapped
    ret = await coro(*args, **kwargs)
  File "PycharmProjects/Unified States/miscRW/credits.py", line 18, in test
    await ctx.send(embed=embed)
  File "guilded/abc.py", line 236, in send
    data = await self._state.create_channel_message(self._channel_id,
  File "guilded/http.py", line 1404, in request
    return await perform()
  File "guilded/http.py", line 1400, in perform
    raise exception(response, data)
guilded.errors.BadRequest: 400 (BadRequestError): data must have required property 'content', data must have required property 'embeds', data must match a schema in anyOf

The above exception was the direct cause of the following exception:
Traceback (most recent call last):
  File "guilded/ext/commands/bot.py", line 421, in invoke
    await ctx.command.invoke(ctx)
  File "guilded/ext/commands/core.py", line 619, in invoke
    await injected(*ctx.args, **ctx.kwargs)
  File "guilded/ext/commands/core.py", line 92, in wrapped
    raise CommandInvokeError(exc) from exc
guilded.ext.commands.errors.CommandInvokeError: Command raised an exception: BadRequest: 400 (BadRequestError): data must have required property 'content', data must have required property 'embeds', data must match a schema in anyOf

**Screenshots**
![image](https://user-images.githubusercontent.com/72110058/174654318-09c68d20-002c-400d-9494-634061ad4e15.png)

**Environment**
 - OS: Arch Linux 2022.06.01 (Development PC) Ubuntu Server Bionic Beaver 18.04.6 LTS (Server)
 - Python version (make sure you're using >=3.8): Python 3.10 Both Environments.
 - Library version: 1.0.0a0 (0.0.5 lacks guilded.ext)

**Comment by shayypy** [comment]
https://github.com/shayypy/guilded.py/issues/33#issuecomment-1122860684
