### ISSUE TITLE
Unable to send Media

### ISSUE THREAD

**Issue by Reedeht** [shayypy/guilded.py#37]
**Describe the bug**
when attempting to send media to show Images or Diagrams, you are unable to send the media

**To Reproduce**
Attempt to send either files or attachments, via await ctx.send or await channel.send... etc

**Expected behavior**
Send message with a Media Attachment of a file.

**Actual behavior**
Message is sent without Media Attachment, and doesn't deliver an error message

**Screenshots**
![image](https://user-images.githubusercontent.com/72110058/174655634-77b622bc-0f85-4e02-9935-1c2b183716b0.png)

**Environment**
- OS: Arch Linux 2022.06.01 (Development PC) Ubuntu Server Bionic Beaver 18.04.6 LTS (Server)
- Python version (make sure you're using >=3.8): Python 3.10 Both Environments.
- Library version: 1.0.0a0 (0.0.5 lacks guilded.ext)

**Comment by shayypy** [comment]
Bots can't send files at the moment
