### ISSUE TITLE
pip broken?

### ISSUE THREAD

**Issue by RioghanDer2te** [shayypy/guilded.py#50]
I couldn't install the newest version of `guilded.py`.
`pip index versions guilded.py` returns
> Available versions: 0.0.5, 0.0.4, 0.0.3, 0.0.2

installing version `1.0.0a0` worked, but it was too outdated.

**Comment by shayypy** [comment]
Make sure your Python is up to date. guilded.py requires 3.8+
```
>py -3.8 -m pip index versions guilded.py
guilded.py (1.6.0)
Available versions: 1.6.0, 1.5.1, 1.5.0, 1.4.0, 1.3.0, 1.2.0, 1.1.0, 0.0.5, 0.0.4, 0.0.3, 0.0.2
  INSTALLED: 1.4.0a0
  LATEST:    1.6.0
```
