### ISSUE TITLE
"Represents a Discord embed." in guilded.Embed docstring

### ISSUE THREAD

**Issue by YumYummity** [shayypy/guilded.py#55]
Unsure if this is intentional. The docstring for `guilded.Embed`'s first line is "Represents a Discord embed."

**Comment by shayypy** [comment]
This was fixed in #51. Use the current version of the docs.

**Comment by YumYummity** [comment]
I'm using the latest on PyPi, which is the March 4 release. That was fixed in February.

> This was fixed in #51. Use the current version of the docs.

**Comment by YumYummity** [comment]
![image](https://user-images.githubusercontent.com/103061664/235377786-4050e6f0-7e6d-4217-94a4-d0829c636187.png)

**Comment by shayypy** [comment]
https://github.com/shayypy/guilded.py/blob/b10361c0556032f0b7429b203e84615aeb7b207a/guilded/embed.py#L88
Make sure your editor's environment is using the latest version.

**Comment by YumYummity** [comment]
> https://github.com/shayypy/guilded.py/blob/b10361c0556032f0b7429b203e84615aeb7b207a/guilded/embed.py#L88
> 
> 
> Make sure your editor's environment is using the latest version.

That fixed it, thanks.
