### ISSUE TITLE
Deleting a message not working

### ISSUE THREAD

**Issue by Ccode-lang** [shayypy/guilded.py#56]
**Describe the bug**
`await message.delete()` returns a 403 error.

**To Reproduce**
Run the command

**Expected behavior**
Deleting the message

**Actual behavior**
It doesn't delete the message.

**Environment**
 - OS: Ubuntu 22.10
 - Python version (make sure you're using >=3.8): 3.10.7
 - Library version: 1.8.0

**Comment by Ccode-lang** [comment]
I did make sure my bot has manage messages.

**Comment by shayypy** [comment]
As continued in the help channel, this is an error from Guilded and not a problem with this library.

**Comment by Ccode-lang** [comment]
I managed to figure it out
