### ISSUE TITLE
Missing typing_extensions module

### ISSUE THREAD

**Issue by martinbndr** [shayypy/guilded.py#59]
**Describe the bug**
Missing required module in the requirements.txt file

**To Reproduce**
Create a new bot project / virtualenv and install guilded.py with ``pip install guilded.py``

**Expected behavior**
Basic bot like provided in the example should work

**Actual behavior**
Error ``ModuleNotFoundError: No module named 'typing_extensions'

**Screenshots**
![image](https://github.com/shayypy/guilded.py/assets/55140357/510af67a-cee7-416f-a70d-09c0b9ab3f77)

**Environment**
 - OS: Windows 10 
 - Python version (make sure you're using >=3.10):
 - Library version: 1.9.0

**Comment by shayypy** [comment]
This should be fixed in https://github.com/shayypy/guilded.py/commit/9b6a33d19b1b4956af2e45c9beb62c5a4c586295, if not please re-open this issue.
