### ISSUE TITLE
Event triggers

### ISSUE THREAD

**Issue by alluding** [shayypy/guilded.py#61]
So, I was making an anti-nuke and anti-raid bot, but it seems like the events don't provide information about the person who triggered the event, which means I can't implement features like whitelisting, etc.

**Comment by shayypy** [comment]
What events in particular, and what information are you expecting? The library attempts to provide as much detail as possible from the data itself

**Comment by alluding** [comment]
> What events in particular, and what information are you expecting? The library attempts to provide as much detail as possible from the data itself

So, for example, I'm monitoring events like `RoleCreateEvent`, and I want to check if the person who triggered this event is whitelisted from the anti-nuke. The thing is, I couldn't find anything relating to how to check who triggered the event. Is it even possible to figure this out?

**Comment by alluding** [comment]
> No, if Guilded doesn't provide it in the [raw event](https://www.guilded.gg/docs/api/websockets/RoleCreated) then libraries can't reliably do so either. I don't think there's any way to see who created a role.


That's unfortunate; I guess I have to scratch off that idea. Anti-raid should work fine. Thank you though.
